name: fencing-token-demo

services:
  # ZooKeeper in a 3-node cluster (odd number of nodes required for quorum majority and to avoid split-brain).
  zoo1:
    image: zookeeper:3.9.5
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
      - 8080:8080
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOOKEEPER_QUORUM_LISTEN_ON_ALL_IPS: 'true'
      # Set the number of maximum of concurrent client connections allowed by Zookeeper.
      ZOO_MAX_CLIENT_CNXNS: 1000

  zoo2:
    image: zookeeper:3.9.5
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
      - 8081:8080
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOOKEEPER_QUORUM_LISTEN_ON_ALL_IPS: 'true'      
      # Set the number of maximum of concurrent client connections allowed by Zookeeper.
      ZOO_MAX_CLIENT_CNXNS: 1000

  zoo3:
    image: zookeeper:3.9.5
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
      - 8082:8080      
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOOKEEPER_QUORUM_LISTEN_ON_ALL_IPS: 'true'      
      # Set the number of maximum of concurrent client connections allowed by Zookeeper.
      ZOO_MAX_CLIENT_CNXNS: 1000

  # Our incredible key-value store (Valkey is the open source BSD-3 fork of Redis)
  redis-server:
    image: valkey/valkey:8.1.7
    restart: always
    hostname: redis-server
    ports:
      - '6379:6379'

  # Graphical Interfaces to Inspect Redis and Zookeeper
  redis-insight:
    image: redis/redisinsight:3.4.2
    restart: always
    hostname: redis-insight
    ports:
      - "5540:5540"

  zoonavigator:
    image: elkozmon/zoonavigator:2.0.0
    restart: always
    hostname: zoo-navigator
    ports:
      - 9000:9000/tcp
    environment:
      HTTP_PORT: 9000